spring.application.name=employee-directory
server.port=8080
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s
spring.thymeleaf.cache=true
build.version=@project.version@
build.git-commit=@git.commit.id@
